name: Angular Build and Deploy

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # Step 3: Install dependencies and build the Angular app
      - name: Build Angular app to prod
        run: |
          npm install
          npm run build:prod

      # Step 4: Clean up worktree and detach prod
      - name: Clean up worktree
        run: |
          git worktree prune
          rm -rf .git/worktrees/*
          git branch -D prod || true

      # Step 5: Debug worktree (optional)
      - name: Debug worktree
        run: git worktree list

      # Step 6: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/browser
          branch: prod
          token: ${{ secrets.GH_TOKEN }}
